# serverless.yml
component: layer

app: example // TODO 修改为应用名称
# 应用阶段
stage: dev
# (必填) 创建的实例名称
name: layer-example // TODO 修改为层名称

inputs:
  name: ${name}
  region: ap-guangzhou # 服务地域
  src:
    src: ../node_modules # 您想要上传到层的项目路径，此处以 node_modules 为例
    targetDir: /node_modules # 上传后的文件打包目录
  runtimes:
    - Nodejs10.15
    - Nodejs12.16
